
//register controller
const registerUser= async (req ,res)=>{
    try{

    }
    catch(e){
        console.log(e);
        res.status(500).json({
            success:false,
            message:'some error occured, please try again later'
        })
    }
}

//login controller
const loginUser= async (req ,res)=>{
    try{

    }
    catch(e){
        console.log(e);
        res.status(500).json({
            success:false,
            message:'some error occured, please try again later'
        })
    }
}
